---
title: "Computer setup instructions"
author: Ben Zipperer
format:
  html:
    code-fold: false
    code-tools:
      source: repo
---

These are just notes to myself to make it easier to set up a new computer. But maybe they are useful to you too!

*Last used: 16 November 2025, Ubuntu 24.04*

## Update everything

```bash
sudo apt update && sudo apt upgrade -y
```
Reboot.

## Dropbox + browser

* [Dropbox](https://www.dropbox.com/install-linux?_tk=install_view) + selective sync
* [Brave](https://brave.com/download/) + sync

## Dotfiles

```bash
# sync dotfiles
sudo apt install stow -y
cd ~/Dropbox/dotfiles
./install.sh
./fix_ssh_perms.sh
```

## Terminal

### zsh 
```bash
sudo apt install zsh curl git -y
chsh -s $(which zsh)
```
Log in and out.

```bash
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
```

```bash
sudo apt install fonts-powerline -y
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
```

### Ghostty

```bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/mkasberg/ghostty-ubuntu/HEAD/install.sh)"
```

## Tailscale

```bash
curl -fsSL https://tailscale.com/install.sh | sh
```
Confirm ssh to machines works.

## Home directory structure

```bash
rmdir ~/Documents ~/Music ~/Templates ~/Videos
mkdir -p ~/data ~/projects ~/.fonts
```

## R

### Latest release

```bash
sudo curl -L https://rig.r-pkg.org/deb/rig.gpg -o /etc/apt/trusted.gpg.d/rig.gpg
sudo sh -c 'echo "deb http://rig.r-pkg.org/deb rig main" > /etc/apt/sources.list.d/rig.list'
sudo apt update
sudo apt install r-rig
```
Then
```bash
rig add release
```

### Packages

Confirm R works and then in R confirm binaries are being downloaded from PPM:
```r
install.packages("usethis")
```
Then
```r
packages = c(
  "arrow",
  "bea.R",
  "crew",
  "devtools",
  "fixest",
  "fs",
  "ipumsr",
  "janitor",
  "modelsummary",
  "openalexR",
  "patchwork",
  "quantreg",
  "slider",
  "tarchetypes",
  "targets",
  "tidyverse",
  "usethis"
)
r_univ_packages = c("epiextractr", "epidatatools", "realtalk")
gh_packages = c(
  "MilesMcBain/breakerofchains",
  "benzipperer/bzipr",
  # includes some additions to Miles McBain's tflow:
  "benzipperer/tflow"
)

install.packages(packages)
install.packages(r_univ_packages, repos = c("https://economic.r-universe.dev", "https://cloud.r-project.org"))
remotes::install_github(gh_packages)

fs::dir_create("~/data/cps")
purrr::walk(c("basic", "org", "may"), ~ epiextractr::download_cps(.x, "~/data/cps"))
```

## Obsidian

```bash
sudo apt install libfuse2 -y
```
Find path to Obsidian AppImage [here](https://obsidian.md/download), then

 ```bash
 mkdir -p ~.local/bin/obsidian
 wget OBSIDIANURL -O ~.local/bin/obsidian/Obsidian.AppImage
 chmod +x ~.local/bin/obsidian/Obsidian.AppImage
 wget https://forum.obsidian.md/uploads/default/optimized/2X/6/6df43bc4ee96f0a1b67ff3600caf6879b758a743_2_500x500.png -O ~/.local/bin/obsidian/icon.png
 update-desktop-database ~/.local/share/applications/
 ```

Confirm desktop entry and icon exist and sync vault to `~/projects/obsidian/notes`. 

Confirm URI handling works
```bash
xdg-open "obsidian://new?vault=notes&name=note&content=content"
```
 ([source](https://amirrachum.com/obsidian-uri-linux/))

## Other stuff

### Misc utilities

```bash
sudo apt install vim pigz python3-venv python3-pip -y
```

### Fonts

```bash
cd ~/.fonts
curl -OL https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip
curl -OL https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.zip
unzip -o JetBrainsMono.zip
rm JetBrainsMono.zip
unzip -o FiraCode.zip
rm FiraCode.zip
fc-cache -fv
```

### Libreoffice

```bash
sudo add-apt-repository ppa:libreoffice/ppa -y
sudo apt install libreoffice -y
```

### Positron

Download .deb from [github](https://github.com/posit-dev/positron/releases).

### Slack

Download .deb from [slack](https://slack.com/downloads/instructions/linux?ddl=1&build=deb)

### Signal

```bash
wget -O- https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor > signal-desktop-keyring.gpg
cat signal-desktop-keyring.gpg | sudo tee /usr/share/keyrings/signal-desktop-keyring.gpg > /dev/null
wget -O signal-desktop.sources https://updates.signal.org/static/desktop/apt/signal-desktop.sources
cat signal-desktop.sources | sudo tee /etc/apt/sources.list.d/signal-desktop.sources > /dev/null
sudo apt update && sudo apt install signal-desktop -y
```
([source](https://signal.org/download))

### AI

For claude code,
```bash
curl -fsSL https://claude.ai/install.sh | bash
```
For gemini, install [nvm](https://github.com/nvm-sh/nvm). Then
```bash
npm install -g @google/gemini-cli
```

### Flatpaks

```bash
sudo apt install flatpak -y
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
```
Reboot. Then install
```bash
flatpak install org.gnome.World.PikaBackup nl.hjdskes.gcolor3
```

### vicinae

```bash
curl -fsSL https://vicinae.com/install.sh | bash
```

## Backups

Use Pika to set up backups to new repository on backup server.

## Update firmware

Confirm system booted in UEFI mode:
```bash
test -d /sys/firmware/efi && echo "UEFI boot OK" || echo "Not UEFI"
```

Confirm EFI system partition mounted at `/boot/efi`:

```bash
findmnt /boot/efi
```
Connect to AC power and check for updates: 
```bash
fwupdmgr refresh --force
fwupdmgr get-updates
```

Apply updates one by one:
```bash
fwupdmgr update
```

Reboot if necessary and confirm updates:
```bash
get-history
```
([source](https://linuxblog.io/upgrade-thinkpad-firmware-linux-fwupd/))